### ISSUE TITLE
Error when reading block data

### ISSUE THREAD

**Issue by alexmorphine** [ctlab/parallel-rearrangements#2]
Hi, I have an error reading block data that is taken from SibeliaZ [output](https://drive.google.com/drive/folders/1595qjF9DVAbeL_hLDEIoK9d2CiJeyBlI)
It actually looks pretty identical to the example you have.

The log is attached:
[output.txt](https://github.com/ctlab/parallel-rearrangements/files/5601735/output.txt)

I am using Windows 10 and Python 3.6.7 (I will try to run it with newer Python today)

**Comment by oxygen311** [comment]
This bug is presented only at Windows machine. So as a hot fix you can try to use UNIX based system or send me full input and I will run tool (provide Newick tree).

I will try to find windows machine and reproduce this bug to fix it.

**Comment by alexmorphine** [comment]
Added tree to Google drive folder :)

**Comment by oxygen311** [comment]
This bug is fixed! Install the new version:
```
pip install PaReBrick==0.1.22
```

If you have other questions, you can write me in telegram @what_a_name
